//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMDUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMDUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color {
            get {
                object obj = ResourceManager.GetObject("color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color_adjustment {
            get {
                object obj = ResourceManager.GetObject("color_adjustment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color_adjustment_green {
            get {
                object obj = ResourceManager.GetObject("color_adjustment_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color_adjustment_red {
            get {
                object obj = ResourceManager.GetObject("color_adjustment_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color_swatch {
            get {
                object obj = ResourceManager.GetObject("color_swatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap color_swatches {
            get {
                object obj = ResourceManager.GetObject("color_swatches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap function {
            get {
                object obj = ResourceManager.GetObject("function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 MMDUI 文件 的本地化字符串。
        /// </summary>
        internal static string IO_Caption {
            get {
                return ResourceManager.GetString("IO.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供 MMDUI 格式的 MME 文件的导入/导出程序。\r\n支持的类型：int / float / float2 / float3 / float4 的本地化字符串。
        /// </summary>
        internal static string IO_Description {
            get {
                return ResourceManager.GetString("IO.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法导入“{1}”，因为它不是 MMDUI 格式。 的本地化字符串。
        /// </summary>
        internal static string IO_FormatException {
            get {
                return ResourceManager.GetString("IO.FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMDUI Format Import/Export 的本地化字符串。
        /// </summary>
        internal static string IO_Name {
            get {
                return ResourceManager.GetString("IO.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_Encoding {
            get {
                return ResourceManager.GetString("Menu.menuItem_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 &amp;ANSI 编码 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_Encoding_ANSI {
            get {
                return ResourceManager.GetString("Menu.menuItem_Encoding_ANSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 &amp;Shift-JIS 编码 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_Encoding_Shift_JIS {
            get {
                return ResourceManager.GetString("Menu.menuItem_Encoding_Shift_JIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 &amp;UTF-8 编码 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_Encoding_UTF_8 {
            get {
                return ResourceManager.GetString("Menu.menuItem_Encoding_UTF_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMDUI(&amp;M) 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_MMDUI {
            get {
                return ResourceManager.GetString("Menu.menuItem_MMDUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 MMDUI(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string Menu_menuItem_MMDUI_About {
            get {
                return ResourceManager.GetString("Menu.menuItem_MMDUI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MMDUI Menu 的本地化字符串。
        /// </summary>
        internal static string Menu_Name {
            get {
                return ResourceManager.GetString("Menu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}：无法编辑此对象。 的本地化字符串。
        /// </summary>
        internal static string MMDUIWidgetBase_IsNotControlObject {
            get {
                return ResourceManager.GetString("MMDUIWidgetBase.IsNotControlObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_color_picker {
            get {
                object obj = ResourceManager.GetObject("ui_color_picker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_color_picker_default {
            get {
                object obj = ResourceManager.GetObject("ui_color_picker_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_color_picker_transparent {
            get {
                object obj = ResourceManager.GetObject("ui_color_picker_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_label {
            get {
                object obj = ResourceManager.GetObject("ui_label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider {
            get {
                object obj = ResourceManager.GetObject("ui_slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider_050 {
            get {
                object obj = ResourceManager.GetObject("ui_slider_050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider_100 {
            get {
                object obj = ResourceManager.GetObject("ui_slider_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider_vertical {
            get {
                object obj = ResourceManager.GetObject("ui_slider_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider_vertical_050 {
            get {
                object obj = ResourceManager.GetObject("ui_slider_vertical_050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_slider_vertical_100 {
            get {
                object obj = ResourceManager.GetObject("ui_slider_vertical_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ui_spin {
            get {
                object obj = ResourceManager.GetObject("ui_spin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供基本的 MMDUI 小部件。\r\n小部件：Color / Numeric / Slider / Spinner 的本地化字符串。
        /// </summary>
        internal static string WidgetProvider_Description {
            get {
                return ResourceManager.GetString("WidgetProvider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Widget Provider 的本地化字符串。
        /// </summary>
        internal static string WidgetProvider_Name {
            get {
                return ResourceManager.GetString("WidgetProvider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Widget Proxy: 无法创建小部件，提供的对象不是“MMDUIObjectFX”。 的本地化字符串。
        /// </summary>
        internal static string WidgetProxy_IsNotMMDUIObjectFX {
            get {
                return ResourceManager.GetString("WidgetProxy.IsNotMMDUIObjectFX", resourceCulture);
            }
        }
    }
}
